//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_service尝试.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        web_service尝试.ServiceReference1.HelloWorldResponse HelloWorld(web_service尝试.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<web_service尝试.ServiceReference1.HelloWorldResponse> HelloWorldAsync(web_service尝试.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JianFa", ReplyAction="*")]
        int JianFa(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JianFa", ReplyAction="*")]
        System.Threading.Tasks.Task<int> JianFaAsync(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChengFa", ReplyAction="*")]
        int ChengFa(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChengFa", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChengFaAsync(int i, int j);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public web_service尝试.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(web_service尝试.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_service尝试.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(web_service尝试.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : web_service尝试.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<web_service尝试.ServiceReference1.WebService1Soap>, web_service尝试.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_service尝试.ServiceReference1.HelloWorldResponse web_service尝试.ServiceReference1.WebService1Soap.HelloWorld(web_service尝试.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            web_service尝试.ServiceReference1.HelloWorldRequest inValue = new web_service尝试.ServiceReference1.HelloWorldRequest();
            inValue.Body = new web_service尝试.ServiceReference1.HelloWorldRequestBody();
            web_service尝试.ServiceReference1.HelloWorldResponse retVal = ((web_service尝试.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web_service尝试.ServiceReference1.HelloWorldResponse> web_service尝试.ServiceReference1.WebService1Soap.HelloWorldAsync(web_service尝试.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<web_service尝试.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            web_service尝试.ServiceReference1.HelloWorldRequest inValue = new web_service尝试.ServiceReference1.HelloWorldRequest();
            inValue.Body = new web_service尝试.ServiceReference1.HelloWorldRequestBody();
            return ((web_service尝试.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int i, int j) {
            return base.Channel.Add(i, j);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int i, int j) {
            return base.Channel.AddAsync(i, j);
        }
        
        public int JianFa(int i, int j) {
            return base.Channel.JianFa(i, j);
        }
        
        public System.Threading.Tasks.Task<int> JianFaAsync(int i, int j) {
            return base.Channel.JianFaAsync(i, j);
        }
        
        public int ChengFa(int i, int j) {
            return base.Channel.ChengFa(i, j);
        }
        
        public System.Threading.Tasks.Task<int> ChengFaAsync(int i, int j) {
            return base.Channel.ChengFaAsync(i, j);
        }
    }
}
