//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WebService2Soap")]
    public interface WebService2Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetWeekResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeek", ReplyAction="*")]
        WebApplication2.ServiceReference3.GetWeekResponse GetWeek(WebApplication2.ServiceReference3.GetWeekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeek", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference3.GetWeekResponse> GetWeekAsync(WebApplication2.ServiceReference3.GetWeekRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeekRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeek", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference3.GetWeekRequestBody Body;
        
        public GetWeekRequest() {
        }
        
        public GetWeekRequest(WebApplication2.ServiceReference3.GetWeekRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeekRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int day;
        
        public GetWeekRequestBody() {
        }
        
        public GetWeekRequestBody(int day) {
            this.day = day;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeekResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeekResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference3.GetWeekResponseBody Body;
        
        public GetWeekResponse() {
        }
        
        public GetWeekResponse(WebApplication2.ServiceReference3.GetWeekResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeekResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeekResult;
        
        public GetWeekResponseBody() {
        }
        
        public GetWeekResponseBody(string GetWeekResult) {
            this.GetWeekResult = GetWeekResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : WebApplication2.ServiceReference3.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference3.WebService2Soap>, WebApplication2.ServiceReference3.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference3.GetWeekResponse WebApplication2.ServiceReference3.WebService2Soap.GetWeek(WebApplication2.ServiceReference3.GetWeekRequest request) {
            return base.Channel.GetWeek(request);
        }
        
        public string GetWeek(int day) {
            WebApplication2.ServiceReference3.GetWeekRequest inValue = new WebApplication2.ServiceReference3.GetWeekRequest();
            inValue.Body = new WebApplication2.ServiceReference3.GetWeekRequestBody();
            inValue.Body.day = day;
            WebApplication2.ServiceReference3.GetWeekResponse retVal = ((WebApplication2.ServiceReference3.WebService2Soap)(this)).GetWeek(inValue);
            return retVal.Body.GetWeekResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference3.GetWeekResponse> WebApplication2.ServiceReference3.WebService2Soap.GetWeekAsync(WebApplication2.ServiceReference3.GetWeekRequest request) {
            return base.Channel.GetWeekAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference3.GetWeekResponse> GetWeekAsync(int day) {
            WebApplication2.ServiceReference3.GetWeekRequest inValue = new WebApplication2.ServiceReference3.GetWeekRequest();
            inValue.Body = new WebApplication2.ServiceReference3.GetWeekRequestBody();
            inValue.Body.day = day;
            return ((WebApplication2.ServiceReference3.WebService2Soap)(this)).GetWeekAsync(inValue);
        }
    }
}
